## <strong> 6. Pandas 객체 생성 및 조작 </strong>

```Pandas``` 라이브러리 설치

In [2]:
!pip install pandas

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.6 MB 1.7 MB/s eta 0:00:07
   ---------------------------------------- 0.1/11.6 MB 1.7 MB/s eta 0:00:07
    --------------------------------------- 0.2/11.6 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.3/11.6 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.4/11.6 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.4/11.6 MB 1.4 MB/s eta 0:00:08
   - -------------------------------------- 0.6/11.6 MB 1.5 MB/s eta 0:00:08
   -- ------------------------------------- 0.6/11.6 MB 1.5 MB/s eta 0:00:08
   -- ------------------------------------- 0.7/11.6 MB 1.4 MB/s eta 0:00:08
   -- ------------------------------------- 0.7/11.6 MB 1.4 MB/s eta 0:00:08
   -- ------------------------------------- 0.7/11.6 MB 1.4 MB/s eta 0:00:08
   -- ------------------------------------- 0.7/11.6 MB 1.4 MB/s eta 0:00:08
   -- 

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# 헬프 문서 출력
pd?

In [4]:
# 라이브러리 버전 확인
pd.__version__

'2.2.3'

### Pandas 객체: <strong> Series </strong>

In [5]:
# [+] List 객체에서 Series 객체를 생성
ser = pd.Series(['asd',123,'asd'])
ser

0    asd
1    123
2    asd
dtype: object

In [6]:
# Pandas 객체 속성: .values
vals = ser.values
vals


array(['asd', 123, 'asd'], dtype=object)

In [7]:
# Pandas 객체 속성: .index
ind = ser.index
print(ind)
print(list(ind))

RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]


In [11]:
# [+] 레이블 기반 인덱싱
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a','b','c','b'])
print(ser)
print(ser['a'])

print(
    ser.index)
print(list(ser.index))

a    0.25
b    0.50
c    0.75
b    1.00
dtype: float64
0.25
Index(['a', 'b', 'c', 'b'], dtype='object')
['a', 'b', 'c', 'b']


### <strong> Dictionary와 Series 객체 </strong>

In [2]:
# Dictionary 객체에서 Series 객체를 생성
population_dict = {
    'California': 38332521,   # 미국 연방주 별 인구
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [7]:
# [+] 레이블 기반 인덱싱: 'California'에서 'New York'까지
population[0:3]
population['California' : 'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Pandas 객체:<strong> DataFrame </strong>

In [ ]:
# 미국 연방주 별 면적
area_dict = {
    'California': 423967,
    'Texas': 695662,
    'New York': 141297,
    'Florida': 170312,
    'Illinois': 149995
}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [11]:
# [+] 'population'과 'area' Series 객체를 포함하는 DataFrame 객체 생성
states = pd.DataFrame({'population': population , 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [12]:
# DataFrame 객체의 인덱스와 컬럼
print(states.index)
print(states.columns)

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object')


In [13]:
# [+] DataFrame으로부터 Series 객체 접근하기
states.columns

Index(['population', 'area'], dtype='object')

#### **NumPy 배열로부터 DataFrame 객체 생성**
+ 예제, 오늘의 운세: 금전운(```money_fortune```), 연애운(```love_fortune```)

In [17]:
# [+] 실수 난수로 이루어진 12X2 크기의 NumPy 배열 생성
arr = np.random.rand(12,2)
arr

array([[0.24738463, 0.43426827],
       [0.3915062 , 0.82153652],
       [0.95998115, 0.72521217],
       [0.50488091, 0.80782142],
       [0.14821459, 0.44541423],
       [0.768565  , 0.95562425],
       [0.81277423, 0.23918684],
       [0.35883782, 0.37832679],
       [0.17233968, 0.56301487],
       [0.05952082, 0.15696858],
       [0.2537728 , 0.63064745],
       [0.81116008, 0.66291767]])

In [19]:
# NumPy 배열로부터 DataFrame 객체 생성
df = pd.DataFrame(
    arr, 
    columns=['money_fortune', 'love_fortune'], 
    index=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
)

df

money_fortune  love_fortune
Jan       0.247385      0.434268
Feb       0.391506      0.821537
Mar       0.959981      0.725212
Apr       0.504881      0.807821
May       0.148215      0.445414
Jun       0.768565      0.955624
Jul       0.812774      0.239187
Aug       0.358838      0.378327
Sep       0.172340      0.563015
Oct       0.059521      0.156969
Nov       0.253773      0.630647
Dec       0.811160      0.662918

### <strong> Series 객체 조작 </strong>

#### Dictionary 스타일 조작

In [33]:
# Series 객체 생성
ser = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print(ser)    
print('a' in ser)   # [+] Key + in 키워드
print(0.25 in ser.values)  # [+] Value + in 키워드
print(ser.index)   # [+] 인덱스
print(ser.keys())   # [+] 키 집합
ser['e'] = 1    # [+] 값 추가
...    # [+] 값 수정
print(ser)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
True
True
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['a', 'b', 'c', 'd'], dtype='object')
a    0.25
b    0.50
c    0.75
d    1.00
e    1.00
dtype: float64


#### 배열 스타일 조작

In [34]:
print(ser['a':'c'])   # 슬라이싱
print(ser[(ser > 0.3) & (ser < 0.8)])   # 논리 연산
# 팬시 인덱싱
ind = ['a', 'e'] 
print(ser[ind])

a    0.25
b    0.50
c    0.75
dtype: float64
b    0.50
c    0.75
dtype: float64
a    0.25
e    1.00
dtype: float64


#### Pandas 객체 인덱싱
+ 정수 기반 인덱싱(암묵적, implicit)
+ 레이블 기반 인덱싱(명시적, explicit)

In [29]:
# 슬라이싱을 이용한 'a', 'b', 'c' 선택
print(ser[0:3])   # 정수 기반 인덱싱
print(ser['a':'c'])     # 레이블 기반 인덱싱

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
c    0.75
dtype: float64


### <strong> DataFrame 객체 조작 </strong>

In [30]:
# 특정 Series 객체 접근
states['area']
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [32]:
# [+] Series 객체 추가 (밀도 = 인구 / 면적)
states['density']=states['population']/states['area']
states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

#### 인덱서: ```loc```, ```iloc```

In [35]:
# Series 객체 생성
ser = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
ser

1    a
3    b
5    c
dtype: object

In [36]:
# loc 인덱서
print(ser.loc[1])
print(ser.loc[1:3])

a
1    a
3    b
dtype: object


In [37]:
# iloc 인덱서
print(ser.iloc[1])
print(ser.iloc[1:3])

b
3    b
5    c
dtype: object


In [38]:
# DataFrame 객체 = 2차원 배열
print(states.values, '\n')        # 값들을 얻어오기
print(states.T, '\n')             # 전치행렬
print(states.iloc[:3, :2], '\n')  # 정수 기반 슬라이싱
print(states.loc[: 'Illinois', : 'population'])  # 레이블 기반 슬라이싱

[[3.83325210e+07 4.23967000e+05 9.04139261e+01]
 [2.64481930e+07 6.95662000e+05 3.80187404e+01]
 [1.96511270e+07 1.41297000e+05 1.39076746e+02]
 [1.95528600e+07 1.70312000e+05 1.14806121e+02]
 [1.28821350e+07 1.49995000e+05 8.58837628e+01]] 

              California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01   

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297 

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135


In [39]:
# 마스킹 + 팬시 인덱싱
states.loc[states.density > 100, ['population', 'density']]

population     density
New York    19651127  139.076746
Florida     19552860  114.806121

In [ ]:
# 값 수정
states.iloc[0, 2] = 90
states

population    area     density
California    38332521  423967   90.000000
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763